dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - libboost-test-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: heroku
  api_key: "$API_KEY"
  run: script

